name: Invoke Backend

on:
  schedule:
    - cron: '*/15 * * * *'  
  workflow_dispatch:

concurrency:
  group: invoke-backend
  cancel-in-progress: true

jobs:
  invoke-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run script
        run: node invoke_backend.mjs
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
