
name: Invoke Backend

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  invoke-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node invoke_backend.mjs
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
